myhosts:
  hosts:
    webvm:
        ansible_host: 100.95.141.52
        ansible_become: yes
        ansible_become_method: sudo
        ansible_connection: ssh
        ansible_user: root #FIXME: once moving from initial mvp test need to move on from this