# pub keys
keys:
- &primary age1ttejqd3tk5gl0fqyz2c0jwe0q7q3m60nlv2c3hcaxtur5tak7e8quwea58
- &hosts: # cat ~/.ssh/ssh_host_ed25519_key.pub | ssh-to-age
    - &stardom age18jn2tw6fkn9cs0j6nc6tlzmtze3xgu9fjv9pv9x7fehxs4x6curs8ce95k
    - &starfief age1e9hhghd2gzvsutxk6e8wyv2c0tdkgyp3avwj3s04n4nm84l8efpsldpemt

creation_rules:
    #path should be relative to location of this file (.sops.yaml)
    - path_regex: secrets.yaml$
      key_groups:
      - age:
        - *primary
        - *stardom
        - *starfief
